/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CJNToken__factory } from "./CJNToken__factory";
export { FaucetTracker__factory } from "./FaucetTracker__factory";
